apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: cartservice-container-kill-schedule
  namespace: chaos-mesh
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 30
  type: PodChaos
  podChaos:
    action: container-kill
    mode: one
    containerNames:
      - server
    selector:
      namespaces:
        - online-boutique
      labelSelectors:
        app: cartservice